name: Build latex sources

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Build document
      uses: dante-ev/latex-action@2021-A
      with:
        root_file: main.tex
        continue_on_error: true
        working_directory: ./
        args: -jobname=result -pdf -f -file-line-error -interaction=nonstopmode
        compiler: latexmk

    - name: Upload PDF document
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: ./result.pdf

  deploy:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: [build]

    steps:

      - name: Variables
        id: vars
        run: |
          echo "date=$(date --date='+3 hours' +'%m-%d')" >> $GITHUB_ENV
          echo "date_and_time=$(date --date='+3 hours' +'%m-%d_%H-%M')" >> $GITHUB_ENV
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: result

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: result-${{ env.date }}-${{ env.sha8 }}
          release_name: Тюленёвник (версия ${{ env.date_and_time }})
          draft: false
          prerelease: false

      # - name: Rename PDF with Russian letters
      #   run: mv ./result.pdf ./Теория_Меры_Уважаемый_${{ env.date_and_time }}.pdf

      - name: Upload PDF asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./result.pdf
          asset_name: Measure_Theory__Respected__${{ env.date_and_time }}.pdf
          asset_content_type: application/pdf
